from datetime import datetime
now = datetime.now()
print("Current time:")
print(now)
print("Current Year:")
print(now.year)
print("Current Month:")
print(now.month)
print("Current Day:")
print(now.day)
print("Current Hour:")
print(now.hour)
print("Current Minute:")
print(now.minute)
print("Current Second:")
print(now.second)